src/main/groovy/com/netflix/spinnaker/gradle/idea/SpinnakerIdeaConfigPlugin.groovy
This also makes IntelliJ select the Gradle wrapper automatically when importing the project.
=> Auto-import libraries when .gradle files change

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/groovy/com/netflix/spinnaker/gradle/ospackage/SpinnakerPackagePlugin.groovy, src/main/groovy/com/netflix/spinnaker/gradle/project/SpinnakerProjectConventionsPlugin.groovy, src/main/resources/META-INF/gradle-plugins/spinnaker.package.properties
Cleans up a bunch of duplication across projects for builds.
See spinnaker/clouddriver#367 for what the packaging build file will look like after this goes in
cc @skorten @diananana
=> Adds spinnaker.package plugin wrapping conventions around building deb/rpm distributions for spinnaker services

build.gradle, src/main/groovy/com/netflix/spinnaker/gradle/ospackage/SpinnakerPackagePlugin.groovy
Fixes the file permissions for the logrotate file
built with this plugin.
The gradle-netflixoss-project-plugin dependency version is pinned
to 3.2.3 because the latest release causes a build-breaking dependency
conflict when using this plugin with clouddriver.
For Spinnaker issue [#904](https://github.com/spinnaker/spinnaker/issues/904)
=> Update logrotate file mode for package plugin

build.gradle
@cfieber ~~I found a copy of the `nl.javadude.gradle.plugins:license-gradle-plugin:0.13.1` transitive dependency in the `http://dl.bintray.com/openmastery/maven` repo, but I'm not sure if it's kosher to link to someone else's bintray account. Can you pull down that dependency and stuff it in `http://spinnaker.bintray.com/gradle`? Is there a preferred method of where to put dependencies?~~
~~Otherwise, we'll need to update each component to include that bintray repo, as I did while trying to test it with Fiat here: https://github.com/ttomsu/fiat/commit/9789dd9b65813c5bbbfb9d9d08e3ca1c3683a294~~ 
I found a copy in the gradle plugin Maven repo. We should still add this to `http://spinnaker.bintray.com/gradle` so that we don't have to add this maven repo to each service.
=> bump netflixoss plugin version

src/main/groovy/com/netflix/spinnaker/gradle/ospackage/OspackageBintrayExtension.groovy, src/main/groovy/com/netflix/spinnaker/gradle/ospackage/OspackageBintrayPublishPlugin.groovy, src/main/groovy/com/netflix/spinnaker/gradle/project/SpinnakerProjectConventionsPlugin.groovy
We'd like to use build numbers to identify unique debian package builds from source with the same semver. Currently `gradle candidate|final` produces a statically-named debian for all version tags with matching semver when using `-Prelease.useLastTag=true`. For example, it ignores the `$metadata` in `X.Y.Z-$metadata` and produces the same `component_X.Y.Z_all.deb` for any value of `$metadata`. This change adds the ability to create a package of the form `component_X.Y.Z-$build_all.deb` where `-PbintrayPackageBuildNumber=$build`. The previous workflows will be unaffected if this flag is not specified.
=> Adds ability to append build numbers to packages.

src/main/groovy/com/netflix/spinnaker/gradle/ospackage/SpinnakerPackagePlugin.groovy
The current package code will take a version like `1.1.1-rc.1` and convert it into `1.1.1`, which will cause conflicts in bintray, as well as falsely release final versions. 
This will produce deb versions like `1.1.1~rc.1`, rather than conflicting versions of repeated `1.1.1`.
@spinnaker/reviewers PTAL
=> fix(package): Don't strip rc version information

src/main/groovy/com/netflix/spinnaker/gradle/ospackage/OspackageBintrayPublishPlugin.groovy
It appears that `1.1.1~rc.1` will be resolved first over `1.0.9`, which we don't want during release candidates for people who are actually using bintray debs. This change would have debs publishing be skipped entirely during release candidates.
@spinnaker/reviewers PTAL
=> fix(ospackage): Skip bintray package upload if release candidate

gradle/wrapper/gradle-wrapper.properties
workaround a bug in the kotlin plugin in the latest intellij release
=> chore(dependencies): update to gradle 3.5

src/main/groovy/com/netflix/spinnaker/gradle/ospackage/OspackageBintrayExtension.groovy, src/main/groovy/com/netflix/spinnaker/gradle/ospackage/OspackageBintrayPublishPlugin.groovy, src/main/groovy/com/netflix/spinnaker/gradle/project/SpinnakerProjectConventionsPlugin.groovy
The Bintray API provides both a synchronous and an asynchronous version of their publish API. We're currently using the asynchronous version, and returning success immediately; this is sometimes causing downstream steps in our build and validate pipleline to fail because they start before the package has actually be published. Change the publish call to be synchronous, so that Gradle task only completes when the publish has completed, and later steps can rely on the existence of the package.
=> fix(publish): Make publish call synchronous

build.gradle, src/main/groovy/com/netflix/spinnaker/gradle/license/SpinnakerLicenseReportPlugin.groovy, src/main/groovy/com/netflix/spinnaker/gradle/project/SpinnakerProjectPlugin.groovy, src/main/resources/META-INF/gradle-plugins/spinnaker.license-report.properties, src/main/resources/license-normalizer-bundle.json
License reports can be run by the `generateLicenseReport` task.
Addresses https://github.com/spinnaker/spinnaker/issues/3294
=> feat(plugin): Add a plugin for third party license report

spinnaker-dev-plugin/build.gradle, spinnaker-dev-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectPlugin.groovy
This PR  adds the plugin to the `spinnaker.base-project`. Scans can be run on demand by running `./gradlew dependencyCheckAggregate`
https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html
=> feat(plugins): Include vulnerability scan plugin to base-project.

spinnaker-gradle-project/src/main/groovy/com/netflix/spinnaker/gradle/project/SpinnakerProjectPlugin.groovy
Undoing the `allprojects` change and releasing
=> fix(builds): Undo switch of rootproject from allprojects

spinnaker-dev-plugin/src/main/groovy/com/netflix/spinnaker/gradle/application/SpinnakerApplicationPlugin.groovy
In boot2, spring.config.location overrides the default instead of adding to it; this means that we're no longer pulling in the default config file for the service.
We could change to using additional-location but this isn't supported for services still on boot1. Instead, just manually add in the default locations (which are the same for boot 1 and 2) before /opt/spinnaker/config. Once we are fully on boot2, we can remove the defaults and change the parameter to additional-locations.
=> fix(*): Make config defaulting comptatible with boot2

spinnaker-dev-plugin/src/main/groovy/com/netflix/spinnaker/gradle/codestyle/SpinnakerCodeStylePlugin.groovy
the autoformatting does whacky things to markdown, no point having it on for them
=> fix(formatter): remove .md files from auto formatting

spinnaker-dev-plugin/src/main/groovy/com/netflix/spinnaker/gradle/codestyle/SpinnakerCodeStylePlugin.groovy
Eliminates spurrious failures against generated content such as swagger.json
=> fix(style): scope spotlessMisc to source files

spinnaker-dev-plugin/src/main/resources/pre-commit
This will re-stage any changed files from applying codestyles that were staged at the time of commit. It won't cover all cases (like the code formatter finding new things that you didn't change), but it's immensely easy to reason about.
=> fix(codestyles): Simplify & fix pre-commit hook

gradle.properties
newer version is required for projects using Gradle 6.0
=> chore(dependencies): update spotless plugin

spinnaker-dev-plugin/src/main/groovy/com/netflix/spinnaker/gradle/codestyle/SpinnakerCodeStylePlugin.groovy
Small request from @emjburns - cut out a rather arbitrary step in having to run `sA` before a `check` - just apply the rules for the developer since they'll have to apply anyway.
=> feat(spotless): Run spotlessApply on check instead of spotlessCheck

gradle.properties
Old versions of spotless do not work with modern gradle:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':spotlessJava'.
at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$Call …
```
=> Upgrade spotless to 3.27.1 to support Gradle 6.+

gradle/kotlin-test.gradle, spinnaker-extensions/build.gradle.kts, spinnaker-extensions/src/functionaltest/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerExtensionGradlePluginFunctionalTest.kt
Mixed casing issue with `functionalTest` on OSX that would cause functional tests to
throw exceptions on run.
Also includes gradle config for the standard kotlin test suite, which I plan to switch things to as I build out more tests for the stuff I jammed in last week.
=> fix(extensions): Fix case-insentivive sourceset resolution

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/extensions/SpinnakerBundleExtension.kt
Not sure where this requirement came from, but we removed it yesterday and I'm just cleaning up the comment here.
=> chore(plugins): Remove comment regarding plugin ID

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerServiceExtensionPlugin.kt
If it is just the service name (orca.plugin-ref) then you have to rename before using multiple plugin refs in orca/plugins or they have name collisions.
=> fix(plugins): plugin ref file name should mention project

spinnaker-dev-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectConventionsPlugin.groovy
Downstream builds should be able to pass in `-PossVersion=1.0.1` for example and set this attribute.
=> feat(version): Add optional property ossVersion to specify Implementation-OSS-Version attribute

spinnaker-dev-plugin/build.gradle, spinnaker-dev-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectPlugin.groovy
The [cross-compiler plugin](https://github.com/nebula-plugins/gradle-java-cross-compile-plugin) requires a little additional setup (you have to set
the JDK_18 environment variable to point at a Java 1.8 JDK) but it fixes an
issue with Groovy and Kotlin compilation, where it prevents you from calling
Java 11 APIs when cross-compiling to Java 8. (For javac, you just have to say
`--release 8`, but setting it up for Groovy and Kotlin is more complicated.)
The Netflix Nebula plugin turns this on automatically, but only for "candidate"
builds, which is why my Java 11 merges succeeded with container builds and PR
GHA builds, but failed with the Debian builds and post-merge GHA builds. (It
failed because we didn't have "JDK_18" set.) So at first I was annoyed about
that because it's going to be a …
=> feat(java11): allow conditionally turning on the cross-compiler plugin

spinnaker-dev-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectConventionsPlugin.groovy
This is already set in fiat, igor, and orca, and I was about to set it
in clouddriver too. Let's just enable it everywhere.
=> chore(javadoc): Don't fail a build because javadoc fails

spinnaker-dev-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectConventionsPlugin.groovy
The closure passed to `withType` is only run _after_ the plugin is actually loaded.
Another approach (used by the Spotless plugin) is to just go ahead and apply the base plugin, but this way seems cleaner to me.
=> fix(base-project): Fix plugin when it's applied before the base plugin

.github/workflows/bump_dependencies.yml, .github/workflows/release.yml
Just for three repositories right now. I just want to start small before
turning it on everywhere. (And all three of these repositories already
have very recent versions of spinnakerGradleVersions.)
=> chore(bumpdeps): enable the bumpdeps workflow

.github/workflows/bump_dependencies.yml
I forgot to update this from the one I was using for testing.
Do you know of any reasonable way to trigger this workflow again for v7.11.0, or do I just have to create a pointless v7.12.0?
=> chore(release): fix the secret name

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerServiceExtensionPlugin.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/AssembleJavaPluginZipTask.kt
PF4J looks to the `lib` directory, not `libs`.
=> fix(plugins): Correctly source dependencies from lib directory

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerServiceExtensionPlugin.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/AssembleJavaPluginZipTask.kt
Now that the dependencies are correctly put in 'lib' and actually used, we can no longer load plugins. This is because the provided (compileOnly) dependencies like kork and spin services are packaged into the plugin and there are classpath issues (duplicate ExtensionConfiguration for example). This change bundles only implementation (compile is included) and runtimeOnly dependencies. Strangely, the "canBeResolved" flag needs to be set on these configs, and a copy of them has to be made first or you get errors about modifying the configs when running unit tests.
I also added the dirs containing the jars to the 'libsDirs' section of the .plugin-ref so that the dependencies are used in debugging mode too.
=> fix(plugins): allow plugin dependencies

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/PublishingPlugin.groovy
adds a candidate and final tasks to trigger the publish workflow so that buildtool
cli invocations work across release branches
=> feat(compat): adds tasks for compatibility with previous plugin version publishing

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/bintray/BintrayCreateVersionTask.groovy, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/bintray/BintrayDebUploadTask.groovy, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/bintray/BintrayPublishExtension.groovy, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/bintray/BintrayPublishPlugin.groovy, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/bintray/BintrayPublishVersionTask.groovy, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/bintray/HttpUtil.groovy
Changes the jar publishing lifecycle:
1. create a version in bintray
2. upload all the artifacts
3. issue a publish command
This eliminates some server side race condition in bintray that
will regularly but randomly result in HTTP 409 responses during
jar publishing where the publish is triggered via the repository
URL `;publish=1` matrix parameter
=> fix(bintrayPublish): change bintray jar lifecycle to fix HTTP errors

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/AssembleUIPluginTask.kt
This reverts a change made in a previous PR.  I misunderstood what this line was doing and this broke bundling of deck plugins.
=> fix(AssembleUIPluginTask): restore this.from().into()

.github/workflows/release.yml
90 seconds isn't long enough; often the artifacts don't show up in bintray yet. I had made this change previously, but I think it got accidentally overwritten in the migration to the new plugin.
=> chore(bumpdeps): increase the pause before running bumpdeps

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/bintray/BintrayPublishExtension.groovy, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/bintray/BintrayPublishPlugin.groovy
This used to happen prior to refactoring things, and I suspect is the reason we see 10 minute dependency times is that
we are currently waiting to see the dependencies sync all the way to jcenter
=> fix(build): add the bintray publish repo as a resolver repo

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/CreatePluginInfoTask.kt, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectConventionsPlugin.groovy
This (along with everything else in `MANIFEST.MF`) got lost when we stopped using Nebula. Halyard was depending on it, so let's put it back.
This fixes part of spinnaker/spinnaker#5740.
=> fix(version): set the Implementation-Version in MANIFEST.MF

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/Plugins.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerServiceExtensionPlugin.kt
**Issue Description**
When you run `./gradlew releaseBundle` it generates the `MANIFEST.MF` file under `build/tmp/jar` and it contains information about the plugin. But if you run any other `gradle` task that involves a build task (ex. `"jar" `task), the plugin information in the `MANIFEST.MF` is removed.
**How to reproduce it**
Run `./gradlew clean releaseBundle `, it will generate the plugin info in the `MANIFEST.MF`. After doing that, run `./gradlew build`  it will remove the plugin info from the `MANIFEST.MF.`
To fix it, i just created a separated task following https://guides.gradle.org/using-build-cache/#suggestions_for_authoring_your_build
=> fix(manifest): Avoid remove plugin data on manifest

build.gradle, spinnaker-project-plugin/build.gradle, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/codestyle/SpinnakerCodeStylePlugin.groovy
There are some minor formatting changes that will need to be applied to each project now. I'll probably kill the bumpdeps action so I can do those manually.
=> chore(formatting): upgrade spotless, ktlint, and google-java-format

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/Flags.groovy, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectConventionsPlugin.groovy
If set, we'll use `-source 11 -target 11` instead of `1.8`. Now that Netflix is moving to the Java 11 runtime, we can start using Java 11 language features. So I'll start migrating all the microservices.
=> feat(javac): add a `targetJava11` project property

spinnaker-extensions/README.md, spinnaker-extensions/build.gradle.kts, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerCompatibilityTestRunnerPlugin.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerExtensionsBundlerPlugin.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerServiceExtensionPlugin.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerUIExtensionPlugin.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/extensions/SpinnakerBundleExtension.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/AssembleJavaPluginZipTask.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/AssembleUIPluginTask.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/BundlePluginsTask.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/CreatePluginInfoTask.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/RegistrationTask.kt, spinnaker-extensions/src/main/resources/META-INF/gradle-plugins/io.spinnaker.plugin.compatibility-test-runner.properties, spinnaker-extensions/src/test/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerExtensionGradlePluginTest.kt
This change is (hopefully) well described in the readme. 
The problem we're trying to solve is that plugin developers don't know which top-level Spinnaker versions their plugin is compatible with. We think plugin developers should be writing Spring Boot-style integration tests that load their plugin inside of a service, and then testing across a range of service versions. This plugin helps with the second half of that problem.
=> feat(plugins): add compatibility test runner

spinnaker-extensions/README.md, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerCompatibilityTestRunnerPlugin.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerVersionsClient.kt, spinnaker-extensions/src/test/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerCompatibilityTestRunnerPluginTest.kt, spinnaker-extensions/src/test/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerExtensionGradlePluginTest.kt
Provides three aliases: `latest`, `nightly`, and `supported`.
=> feat(tests): allow version aliases in compatibility block

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerServiceExtensionPlugin.kt
This PR ensure that a version is included in the MANIFEST.
In some plugins, the value of the plugin bundler extension is set as `unspecified` so kork project is not able to compare version correctly.
I made these changes following the implementation to create `plugin-info.json` here: https://github.com/spinnaker/spinnaker-gradle-project/blob/ec00e146cb66d03f69b4f9bcae5c6cc7a437a485/spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/CreatePluginInfoTask.kt#L68
=> fix(manifest): include rootProject version when the extension version is unspecified

spinnaker-extensions/src/functionaltest/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerExtensionGradlePluginFunctionalTest.kt, spinnaker-extensions/src/functionaltest/kotlin/com/netflix/spinnaker/gradle/extension/fixture.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/compatibility/SpinnakerCompatibilityTestRunnerPlugin.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/extensions/SpinnakerBundleExtension.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/extensions/SpinnakerCompatibilityExtension.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/extensions/dsl.kt, spinnaker-extensions/src/test/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerCompatibilityTestRunnerPluginTest.kt
The goal here is to allow plugin developers to run tests against Spinnaker versions that their plugin may or may not be compatible with.
=> feat(compatibility): allow optional tests

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/bintray/BintrayPublishExtension.groovy
Prior to this fix, any intended boolean project property (ie. `-PbintrayPublishDebEnabled`) would
be interpreted as `true` apparently due to how `asType()` works.
=> fix(*): Support for parsing boolean project properties

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectConventionsPlugin.groovy
I think it makes sense to sort maven central below jcenter for now so that ideally that only thing we're pulling from maven is the new `io.spinnaker` coordinates.
=> feat(conventions): include maven central as a default repository

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectConventionsPlugin.groovy
and slows builds way down.
Note that there are more references to jcenter here. This is an attempt to fix publishing of jars to nexus, or at least reduce log noise when doing that...so that we can eventually remove the remaining references and actually have tests pass.
=> chore(build): remove jcenter since it always responds with 403

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerUIExtensionPlugin.kt
Running `yarnBuild` should also run `yarnModules`
=> fix(build): update to use dependsOn over mustRunAfter

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/bintray/BintrayPublishExtension.groovy
When enabled, this plugin adds a maven repo named bintraySpinnakerRepo using url
https://dl.bintray.com/spinnaker/spinnaker/ (it's configurable, but that's the default).
The response from that url is a 403 now that bintray is gone (https://status.bintray.com/)
so there's no point in looking there for maven artifacts.
Eventually it likely makes sense to remove this entire plugin, but this seems like a quick
way to move forward for now.
=> chore(build): disable the bintray publish plugin

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectPlugin.groovy, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/PublishingPlugin.groovy
Adds license information to generated POMs. This is useful for us as our procurement tooling checks the POM for a license. If a license is not found in the POM then we have to get the license manually verified (which is a massive pain when procuring a lot of dependencies for a new version).
The addition looks like this:
```
<licenses>
<license>
<name>Apache License, Version 2.0</name>
<url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
<distribution>repo</distribution>
</license>
</licenses>
```
=> chore(build): add license information to generated POMs

spinnaker-extensions/README.md, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/Plugins.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/ProjectHelper.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerServiceExtensionPlugin.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/compatibility/SpinnakerCompatibilityTestRunnerPlugin.kt, spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/tasks/CreatePluginInfoTask.kt
The current gradle extensions assume that the project structure is similar to
```
rootProject (plugin: io.spinnaker.plugin.bundler)
|-- deck (plugin: io.spinnaker.plugin.ui-extension)
|-- orca (plugin: io.spinnaker.plugin.service-extension)
```
This assumption of project structure and the use of `project.rootProject` prevent creating a monorepo for all an organizations plugins.
By changing the reference from `project.rootProject` to `project.parent` with fallback to `project.rootProject` this supports deeper project structures and a monorepo of Spinnaker Plugins
Example
```
rootProject (plugin: none)
|--plugins
|  |--plugin1 (plugin: io.spinnaker.plugin.bundler)
|  |  |-- deck (plugin: io.spinnaker.plugin.ui-extension)
|  |  |-- orca (plugin: io.spinnaker.plugin.service-extension)
| …
```
=> Support for monorepo project structures

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/artifactregistry/ArtifactRegistryPublishExtension.groovy
Without this, boolean properties are interpreted as true even when specified as false.
Similar to https://github.com/spinnaker/spinnaker-gradle-project/pull/158
=> fix(publishing/artifactory): support parsing boolean project properties

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/artifactregistry/ArtifactRegistryDebPublishTask.java
as required by ImportAptArtifacts as described here: https://cloud.google.com/artifact-registry/docs/reference/rpc/google.devtools.artifactregistry.v1beta2
=> fix(publishing): set scope for google credentials

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerUIExtensionPlugin.kt
The hardcoded direct yarn call doesn't play very nicely on Windows. By allowing the command to be overridden we can specify either a full path or "yarm.cmd" which seems to be recommended for Windows.
=> feat(build): allow overriding yarn command

spinnaker-extensions/src/functionaltest/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerExtensionGradlePluginFunctionalTest.kt, spinnaker-extensions/src/functionaltest/kotlin/com/netflix/spinnaker/gradle/extension/fixture.kt
now that a version of spinnaker has been released (1.27.0) that has artifacts published in
a live artifact repo (maven central).
This effectively reverts https://github.com/spinnaker/spinnaker-gradle-project/pull/167.
=> chore(plugins): re-enable spinnaker-extensions compatibility tests

spinnaker-project-plugin/build.gradle, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/artifactregistry/ArtifactRegistryDebPublishTask.java, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/artifactregistry/ArtifactRegistryPublishExtension.groovy
Also widened the default timeout for polling for imports based on recent builds timing out. There is some intertwining of dependencies between what the GCS lib and the artifact registry are using so I had to upgrade both.
=> chore(publishing): upgrade artifact registry jar

.github/workflows/build.yml, .github/workflows/pr.yml, .github/workflows/release.yml
and generally bring actions up to date.
See also https://github.com/spinnaker/rosco/pull/909.
=> chore(gha): replace deprecated set-output and save-state commands

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/application/SpinnakerApplicationPlugin.groovy
With spring boot 2.4, spring location properties will no longer fail silently if the file or folder does not exist. Now, requires prefix "optional:" for the location.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#config-file-processing-application-properties-and-yaml-files
And introducing new spring additional data importing property suggested below, to be used with Spring boot 2.4: 
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide 
https://docs.spring.io/spring-boot/docs/2.4.0/reference/html/spring-boot-features.html#boot-features-external-config-files-importing
=> fix(plugin): Issue with non-existing file/folder location used in Spring properties while upgrading spring boot 2.4.x.

build.gradle, spinnaker-project-plugin/build.gradle
since there's no groovy code to compile.
As well, this means no more groovydoc generation, which, with any luck, will mean we no longer get errors like
```
Execution failed for task ':spinnaker-extensions:publishPlugins'.
> Failed to post to server.
Server responded with:
Invalid publication, you have different artifacts with the same hash: (JAVADOC and GROOVYDOC). Support for this is only available with version 1.0+ of the plugin-publish plugin.
```
from https://github.com/spinnaker/spinnaker-gradle-project/actions/runs/3753925474/jobs/6377662818
Attempts to upgrade the plugin-publish plugin to 1.0+ weren't straightforward, so here we are.
=> refactor(build): stop applying groovy plugin

spinnaker-extensions/build.gradle.kts
Hi folks!
I found that current used checksum gradle plugin version fails in modern Gradle versions with the following:
```
Cannot use @TaskAction annotation on method Checksum.generateChecksumFiles() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```
`IncrementalTaskInputs` are removed. However, I found that the plugin author already has 1.4.0 which includes https://github.com/gradle/gradle-checksum/commit/54d922bb2d1fb70fcf3a4bff64abb267476930b3 that solves the problem
=> chore(deps): Upgrade org.gradle.crypto.checksum.gradle.plugin to support Gradle 8

spinnaker-extensions/build.gradle.kts, spinnaker-extensions/src/functionaltest/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerExtensionGradlePluginFunctionalTest.kt
to pave the way to use e.g. @ParameterizedTest.
Both before and after the change the number of tests executed are the same.
test:
functionalTest:
=> chore(extensions/test): upgrade from junit4 to junit5

spinnaker-extensions/build.gradle.kts, spinnaker-extensions/src/functionaltest/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerExtensionGradlePluginFunctionalTest.kt
In order to facilitate the process of upgrading gradle version from 6.x to 7.x, extend the existing tests with gradle version compatibility check.
=>  test(extensions): demonstrate gradle version 6.x and 7.x compatibility of gradle plugins

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/project/SpinnakerProjectPlugin.groovy
While executing the build script with --warning-mode=fail for fiat, gate, clouddriver, orca, front50, igor, echo and halyard received below error:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0
```
And the common deprecated gradle feature is:
```
Copying or archiving duplicate paths with the default duplicates strategy has been deprecated. This is scheduled to be removed in Gradle 7.0. Explicitly set the duplicates strategy to 'DuplicatesStrategy.INCLUDE' if we want to allow duplicate paths. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.3/userguide/upgrading_version_5.html#implicit_duplicate_strategy_for_copy_or_archive_tasks_has_been_deprecated
```
The issue is raised by `processResources` and `sourceJar` …
=> refactor(deprecation): remove deprecated gradle constructs/features to be consumed by other spinnaker components

spinnaker-extensions/src/main/kotlin/com/netflix/spinnaker/gradle/extension/SpinnakerUIExtensionPlugin.kt
This reverts commit d2b3f2ea940204144f20164c0a17fb253f2f20d2.
I broke frontend plugins, no yarn modules command exists 😓  https://github.com/spinnaker/spinnaker-gradle-project/pull/166
=> Revert "chore(deck): add yarn modules call before yarn build (#166)"

build.gradle, spinnaker-project-plugin/build.gradle, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/codestyle/SpinnakerCodeStylePlugin.groovy
While upgrading the gradle wrapper to 7.6.1 for spinnaker services, all the services (clouddriver, gate, igor, echo, front50, fiat, halyard, rosco, kayenta, orca) faced below warning related to spotlessMisc task ordering (a sample from igor):
```
> Task :spotlessMisc
Execution optimizations have been disabled for task ':spotlessMisc' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/gradle-upgrade-7.x/gradle7/igor'. Reason: Task ':spotlessMisc' uses this output of task ':spotlessJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6.1/userguide/validation_problems.html#implicit_depend …
```
=> chore(dependencies): upgrade com.diffplug.spotless:spotless-plugin-gradle and associated dependencies of google-java-format and ktlint

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/artifactregistry/ArtifactRegistryDebPublishTask.java
to remove error:
```
A problem was found with the configuration of task ':halyard-web:publishDebToArtifactRegistry' (type 'ArtifactRegistryDebPublishTask').
- In plugin 'com.netflix.spinnaker.gradle.baseproject.SpinnakerBaseProjectConventionsPlugin' type 'com.netflix.spinnaker.gradle.publishing.artifactregistry.ArtifactRegistryDebPublishTask' property 'aptImportTimeoutSeconds' is missing an input or output annotation.
Reason: A property without annotation isn't considered during up-to-date checking.
Possible solutions:
1. Add an input or output annotation.
2. Mark it as @Internal.
Please refer to https://docs.gradle.org/7.6.1/userguide/validation_problems.html#missing_annotation for more details about this problem.
```
=> fix(publishing): add @Input annotation to getAptImportTimeoutSeconds

build.gradle, spinnaker-project-plugin/build.gradle
To get around https://github.com/diffplug/spotless/issues/834 error when compiling with JDK 17.
=> fix(java17): upgrade Spotless to support JDK 17

spinnaker-project-plugin/build.gradle, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/Flags.groovy, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectConventionsPlugin.groovy, spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectPlugin.groovy
Taking heavy inspiration from @plumpy (https://github.com/spinnaker/spinnaker-gradle-project/pull/149)
=> feat(java17): conditional compilation to Java 17 bytecode

spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/baseproject/SpinnakerBaseProjectConventionsPlugin.groovy
I don't know how Spotless was working previously, but >=6.0.0 changed how repositories are sourced. Modules without the `java-library` are now failing as they have no repositories defined.
By moving this call out of the if statement we add `mavenCentral` to all modules and resolve this issue.
=> fix(build): add mavenCentral repository to all modules to fix Spotless
